#!/usr/bin/env bash
# Bash script that will display information about the subdomains

dns_config () {
    local domain="$1"
    local subdomain="$2"
    local dig_output

    if dig_output=$(dig "$subdomain.$domain" +short); then
        local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
        echo "The subdomain $subdomain is a $record_type record and points to $dig_output"
    else
        echo "Error: Unable to retrieve DNS information for $subdomain.$domain"
    fi
}

if [ "$#" -eq 1 ]; then
    dns_config "$1" "www"
    dns_config "$1" "lb-01"
    dns_config "$1" "web-01"
    dns_config "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    dns_config "$@"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

