#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

display_info() {
    dig_output=$(dig $1.$2 | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $1 is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    display_info www "$domain"
    display_info lb-01 "$domain"
    display_info web-01 "$domain"
    display_info web-02 "$domain"
else
    display_info "$subdomain" "$domain"
fi

