#!/usr/bin/env bash

openssl genpkey -algorithm RSA -out school.pem -aes256 -pass pass:betty -aes-256-cbc -pkeyopt rsa_keygen_bits:4096

# Extract public key from the private key
openssl rsa -pubout -in school.pem -out school.pub.pem

